/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-primary-container": "#e7eaff",
        "surface": "#fcf9f8",
        "surface-container-highest": "#e5e2e1",
        "tertiary-fixed": "#8cf9ae",
        "on-primary-fixed-variant": "#003da9",
        "surface-container-lowest": "#ffffff",
        "on-primary-fixed": "#00174b",
        "tertiary-fixed-dim": "#70dc93",
        "secondary-container": "#d9dff5",
        "on-tertiary-fixed": "#00210d",
        "inverse-surface": "#313030",
        "outline": "#737687",
        "on-secondary-container": "#5c6274",
        "primary-fixed-dim": "#b4c5ff",
        "tertiary": "#005f31",
        "on-background": "#1c1b1b",
        "on-tertiary-fixed-variant": "#00522a",
        "on-surface": "#1c1b1b",
        "surface-dim": "#dcd9d9",
        "on-surface-variant": "#434655",
        "surface-tint": "#0052dc",
        "primary-container": "#155eef",
        "secondary-fixed": "#dce2f7",
        "surface-bright": "#fcf9f8",
        "on-error-container": "#93000a",
        "inverse-on-surface": "#f3f0ef",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#a2ffbb",
        "secondary-fixed-dim": "#c0c6db",
        "error": "#ba1a1a",
        "surface-container-low": "#f6f3f2",
        "surface-variant": "#e5e2e1",
        "secondary": "#575e70",
        "surface-container-high": "#ebe7e7",
        "inverse-primary": "#b4c5ff",
        "outline-variant": "#c3c6d8",
        "on-secondary": "#ffffff",
        "surface-container": "#f0edec",
        "on-secondary-fixed": "#141b2b",
        "error-container": "#ffdad6",
        "on-error": "#ffffff",
        "on-primary": "#ffffff",
        "primary-fixed": "#dbe1ff",
        "background": "#fcf9f8",
        "tertiary-container": "#007a41",
        "primary": "#0047c1",
        "on-secondary-fixed-variant": "#404758"
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px"
      },
      spacing: {
        "space-xl": "1.5rem",
        "margin-tablet": "1.5rem",
        "space-md": "0.75rem",
        "margin": "1rem",
        "space-xs": "0.25rem",
        "space-sm": "0.5rem",
        "gutter-desktop": "1.5rem",
        "margin-desktop": "2rem",
        "gutter": "1rem",
        "space-lg": "1rem"
      },
      fontFamily: {
        "body-sm": ["Inter", "sans-serif"],
        "label-code-sm": ["JetBrains Mono", "monospace"],
        "label-code-md": ["JetBrains Mono", "monospace"],
        "body-lg": ["Inter", "sans-serif"],
        "headline-lg-mobile": ["Inter", "sans-serif"],
        "label-code-lg": ["JetBrains Mono", "monospace"],
        "headline-sm": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "display-lg": ["Inter", "sans-serif"]
      },
      fontSize: {
        "body-sm": ["12px", { lineHeight: "18px", fontWeight: "400" }],
        "label-code-sm": ["10px", { lineHeight: "14px", letterSpacing: "0.04em", fontWeight: "500" }],
        "label-code-md": ["12px", { lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "500" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", letterSpacing: "-0.015em", fontWeight: "700" }],
        "label-code-lg": ["14px", { lineHeight: "20px", letterSpacing: "0.02em", fontWeight: "600" }],
        "headline-sm": ["16px", { lineHeight: "24px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-md": ["20px", { lineHeight: "28px", letterSpacing: "-0.015em", fontWeight: "600" }],
        "headline-lg": ["28px", { lineHeight: "36px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "display-lg": ["36px", { lineHeight: "44px", letterSpacing: "-0.025em", fontWeight: "700" }]
      }
    },
  },
  plugins: [],
}
